package pl.michalkruczek.learn.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CATEGORY".
 */
@Entity
public class Category {

    @Id(autoincrement = true)
    private Long id;
    private String value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    @Generated
    public Category(Long id, String value) {
        this.id = id;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString(){
        return getValue();
    }
    // KEEP METHODS END

}
