package pl.michalkruczek.learn.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import pl.michalkruczek.learn.db.Category;
import pl.michalkruczek.learn.db.Question;

import pl.michalkruczek.learn.db.CategoryDao;
import pl.michalkruczek.learn.db.QuestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig questionDaoConfig;

    private final CategoryDao categoryDao;
    private final QuestionDao questionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Question.class, questionDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        questionDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

}
